# Site settings
title: Notifiex
tag_text: Notifiex
description: Notifiex docs.
url: ""
baseurl: ""
remote_theme: pmarsceill/just-the-docs
font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
