# Site settings
title: Notifiex
tag_text: Notifiex
description: Notifiex docs.
url: "https://burntcarrot.github.io/notifiex/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
